# Generated by Django 4.2.7 on 2024-02-19 13:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desciption',
            field=tinymce.models.HTMLField(),
        ),
    ]
