# Generated by Django 4.2.7 on 2024-02-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webport', '0002_alter_project_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='Projectimage/'),
        ),
        migrations.CreateModel(
            name='ProjectImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstImg', models.ImageField(upload_to='Projectimage/')),
                ('secondImg', models.ImageField(upload_to='Projectimage/')),
                ('thirdImg', models.ImageField(upload_to='Projectimage/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webport.project')),
            ],
        ),
    ]
