# Generated by Django 4.2.7 on 2024-02-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webport', '0005_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeimg', models.FileField(upload_to='Resumes/')),
                ('profilepic', models.ImageField(upload_to='Resumes/')),
            ],
        ),
    ]
