# Generated by Django 4.2.7 on 2024-02-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webport', '0006_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resumeimg',
            new_name='resumeFile',
        ),
    ]
