# Generated by Django 4.2.7 on 2024-02-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webport', '0007_rename_resumeimg_resume_resumefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='Resumes/'),
        ),
    ]
