# Generated by Django 5.0.4 on 2024-04-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webport', '0009_rename_link_project_githublink_project_livelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalvisiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counting', models.IntegerField(default=0)),
            ],
        ),
    ]
